version: 1.0.{build}
build: false
platform: x64

services:
  - postgresql101

environment:
  distutils_use_sdk: 1
  sdkver: "v7.0"
  PGPORT: "5432"
  PGHOST: "localhost"
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

test_script:
  - SET PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - psql -h 127.0.0.1 -p 5432 -c "CREATE DATABASE ccloud_test;"
  - SET PATH=%APPVEYOR_BUILD_FOLDER%;%PATH%
  - cmd: make.cmd test
