version: 1.0.{build}
init:
- ps: if (!(test-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community")) {Write-host ".NET Core tests require VS 2017"; Exit-AppveyorBuild}
image: Visual Studio 2017
platform:
  - AnyCPU
test_script: 
  - cmd: dir "C:\projects\unit-test-runners\DotNetCore-xUnit\bin\"
  - ps: dotnet test "C:\projects\unit-test-runners\DotNetCore-xUnit\DotNetCore-xUnit.csproj" --no-build 
  
install:
- nuget
- cmd: nuget restore
build:
  verbosity: minimal
#on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
