version: 1.0.{build}
#image: Visual Studio 2017
services:
  - postgresql101


init:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#- ps: if (!(test-path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community")) {Write-host ".NET Core tests require VS 2017"; Exit-AppveyorBuild}

platform:
  - x64
test_script:
   - set PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
   - psql -h 127.0.0.1 -p 5432 -c "CREATE DATABASE ccloud_test;"
 # - cmd: set PLATFORM=AnyCPU
  #- ps: dotnet test "C:\projects\unit-test-runners\DotNetCore-xUnit\DotNetCore-xUnit.csproj" --no-build 
  
install:
#- nuget
- cmd: nuget restore
build:
  verbosity: minimal
#on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
